# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/main.ui',
# licensing of 'designer/main.ui' applies.
#
# Created: Sat Feb  9 20:25:12 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(QtCore.QObject):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 502)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fileBox = QtWidgets.QGridLayout()
        self.fileBox.setContentsMargins(20, 10, 20, 10)
        self.fileBox.setObjectName("fileBox")
        self.fileButton = QtWidgets.QPushButton(self.centralwidget)
        self.fileButton.setObjectName("fileButton")
        self.fileBox.addWidget(self.fileButton, 0, 3, 1, 1)
        self.fileEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.fileEdit.setEnabled(True)
        self.fileEdit.setReadOnly(True)
        self.fileEdit.setObjectName("fileEdit")
        self.fileBox.addWidget(self.fileEdit, 0, 1, 1, 1)
        self.fileLabel = QtWidgets.QLabel(self.centralwidget)
        self.fileLabel.setObjectName("fileLabel")
        self.fileBox.addWidget(self.fileLabel, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.fileBox)
        self.sliderBox = QtWidgets.QHBoxLayout()
        self.sliderBox.setContentsMargins(20, 10, 20, 10)
        self.sliderBox.setObjectName("sliderBox")
        self.positionLabel = QtWidgets.QLabel(self.centralwidget)
        self.positionLabel.setObjectName("positionLabel")
        self.sliderBox.addWidget(self.positionLabel)
        self.timeSlider = QtWidgets.QSlider(self.centralwidget)
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setObjectName("timeSlider")
        self.sliderBox.addWidget(self.timeSlider)
        self.timeLabel = QtWidgets.QLabel(self.centralwidget)
        self.timeLabel.setObjectName("timeLabel")
        self.sliderBox.addWidget(self.timeLabel)
        self.verticalLayout.addLayout(self.sliderBox)
        self.controllerBox = QtWidgets.QGridLayout()
        self.controllerBox.setContentsMargins(20, 10, 20, 10)
        self.controllerBox.setObjectName("controllerBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.endLabel = QtWidgets.QLabel(self.centralwidget)
        self.endLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.endLabel.setObjectName("endLabel")
        self.verticalLayout_3.addWidget(self.endLabel)
        self.endEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.endEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.endEdit.setReadOnly(True)
        self.endEdit.setObjectName("endEdit")
        self.verticalLayout_3.addWidget(self.endEdit)
        self.endButton = QtWidgets.QPushButton(self.centralwidget)
        self.endButton.setObjectName("endButton")
        self.verticalLayout_3.addWidget(self.endButton)
        self.controllerBox.addLayout(self.verticalLayout_3, 0, 3, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.startLabel = QtWidgets.QLabel(self.centralwidget)
        self.startLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.startLabel.setObjectName("startLabel")
        self.verticalLayout_2.addWidget(self.startLabel)
        self.startEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.startEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.startEdit.setReadOnly(True)
        self.startEdit.setObjectName("startEdit")
        self.verticalLayout_2.addWidget(self.startEdit)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.verticalLayout_2.addWidget(self.startButton)
        self.controllerBox.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setObjectName("playButton")
        self.controllerBox.addWidget(self.playButton, 0, 0, 1, 1)
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setObjectName("backButton")
        self.controllerBox.addWidget(self.backButton, 0, 4, 1, 1)
        self.forwardButton = QtWidgets.QPushButton(self.centralwidget)
        self.forwardButton.setObjectName("forwardButton")
        self.controllerBox.addWidget(self.forwardButton, 0, 5, 1, 1)
        self.pauseButton = QtWidgets.QPushButton(self.centralwidget)
        self.pauseButton.setObjectName("pauseButton")
        self.controllerBox.addWidget(self.pauseButton, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.controllerBox)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        spacerItem = QtWidgets.QSpacerItem(0, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.settingsBox = QtWidgets.QHBoxLayout()
        self.settingsBox.setContentsMargins(20, 10, 20, 10)
        self.settingsBox.setObjectName("settingsBox")
        self.normalizeLabel = QtWidgets.QLabel(self.centralwidget)
        self.normalizeLabel.setObjectName("normalizeLabel")
        self.settingsBox.addWidget(self.normalizeLabel)
        self.normalizeEdit = QtWidgets.QSpinBox(self.centralwidget)
        self.normalizeEdit.setMinimum(-100)
        self.normalizeEdit.setMaximum(0)
        self.normalizeEdit.setProperty("value", -6)
        self.normalizeEdit.setObjectName("normalizeEdit")
        self.settingsBox.addWidget(self.normalizeEdit)
        self.normalizeCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.normalizeCheckbox.setChecked(True)
        self.normalizeCheckbox.setObjectName("normalizeCheckbox")
        self.settingsBox.addWidget(self.normalizeCheckbox)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.settingsBox.addWidget(self.line)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setObjectName("titleLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.titleLabel)
        self.artistLabel = QtWidgets.QLabel(self.centralwidget)
        self.artistLabel.setObjectName("artistLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.artistLabel)
        self.albumLabel = QtWidgets.QLabel(self.centralwidget)
        self.albumLabel.setObjectName("albumLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.albumLabel)
        self.titleEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.titleEdit.setObjectName("titleEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.titleEdit)
        self.artistEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.artistEdit.setObjectName("artistEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.artistEdit)
        self.albumEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.albumEdit.setText("")
        self.albumEdit.setObjectName("albumEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.albumEdit)
        self.genreLabel = QtWidgets.QLabel(self.centralwidget)
        self.genreLabel.setObjectName("genreLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.genreLabel)
        self.genreEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.genreEdit.setText("")
        self.genreEdit.setObjectName("genreEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.genreEdit)
        self.settingsBox.addLayout(self.formLayout)
        self.verticalLayout.addLayout(self.settingsBox)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(20, 10, 20, 10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.exportLabel = QtWidgets.QLabel(self.centralwidget)
        self.exportLabel.setObjectName("exportLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.exportLabel)
        self.exportEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportEdit.sizePolicy().hasHeightForWidth())
        self.exportEdit.setSizePolicy(sizePolicy)
        self.exportEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.exportEdit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.exportEdit.setBaseSize(QtCore.QSize(0, 0))
        self.exportEdit.setObjectName("exportEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.exportEdit)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.exportBox = QtWidgets.QHBoxLayout()
        self.exportBox.setContentsMargins(20, 10, 20, 10)
        self.exportBox.setObjectName("exportBox")
        self.exportButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportButton.setObjectName("exportButton")
        self.exportBox.addWidget(self.exportButton)
        self.verticalLayout.addLayout(self.exportBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuMeny = QtWidgets.QMenu(self.menubar)
        self.menuMeny.setObjectName("menuMeny")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSet_FFMPEG = QtWidgets.QAction(MainWindow)
        self.actionSet_FFMPEG.setObjectName("actionSet_FFMPEG")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setEnabled(False)
        self.actionAbout.setObjectName("actionAbout")
        self.actionShortcuts = QtWidgets.QAction(MainWindow)
        self.actionShortcuts.setEnabled(False)
        self.actionShortcuts.setObjectName("actionShortcuts")
        self.actionSet_export = QtWidgets.QAction(MainWindow)
        self.actionSet_export.setObjectName("actionSet_export")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMeny.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionSet_export)
        self.menuHelp.addAction(self.actionShortcuts)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuMeny.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "SermonCut", None, -1))
        self.fileButton.setText(QtWidgets.QApplication.translate("MainWindow", "Choose file", None, -1))
        self.fileLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Input file:", None, -1))
        self.positionLabel.setText(QtWidgets.QApplication.translate("MainWindow", "0:00:00", None, -1))
        self.timeLabel.setText(QtWidgets.QApplication.translate("MainWindow", "0:00:00", None, -1))
        self.endLabel.setText(QtWidgets.QApplication.translate("MainWindow", "End of sermon:", None, -1))
        self.endEdit.setText(QtWidgets.QApplication.translate("MainWindow", "-:--:--", None, -1))
        self.endButton.setText(QtWidgets.QApplication.translate("MainWindow", "Set endtime", None, -1))
        self.startLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Start of sermon:", None, -1))
        self.startEdit.setText(QtWidgets.QApplication.translate("MainWindow", "-:--:-", None, -1))
        self.startButton.setText(QtWidgets.QApplication.translate("MainWindow", "Set starttime", None, -1))
        self.playButton.setText(QtWidgets.QApplication.translate("MainWindow", "Play", None, -1))
        self.backButton.setText(QtWidgets.QApplication.translate("MainWindow", "Back 30s", None, -1))
        self.forwardButton.setText(QtWidgets.QApplication.translate("MainWindow", "Forward 30s", None, -1))
        self.pauseButton.setText(QtWidgets.QApplication.translate("MainWindow", "Pause", None, -1))
        self.normalizeLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Normalize level [dB]", None, -1))
        self.normalizeCheckbox.setText(QtWidgets.QApplication.translate("MainWindow", "Normalize Audio", None, -1))
        self.titleLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Title", None, -1))
        self.artistLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Artist", None, -1))
        self.albumLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Album", None, -1))
        self.genreLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Genre", None, -1))
        self.exportLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Outputfile:", None, -1))
        self.exportButton.setText(QtWidgets.QApplication.translate("MainWindow", "Export to mp3", None, -1))
        self.menuMeny.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuSettings.setTitle(QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
        self.actionSet_FFMPEG.setText(QtWidgets.QApplication.translate("MainWindow", "Set ffmpeg folder", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About SermonCut", None, -1))
        self.actionShortcuts.setText(QtWidgets.QApplication.translate("MainWindow", "Keyboard commands", None, -1))
        self.actionSet_export.setText(QtWidgets.QApplication.translate("MainWindow", "Set export folder", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))

